### ISSUE TITLE
optimize sdk generate block api

### ISSUE THREAD

**Issue by zengchen221** [qlcchain/qlc-go-sdk#34] opened 2019-11-11 02:03 UTC
@zengchen221 commented on [Mon Nov 11 2019](https://github.com/qlcchain/go-qlc/issues/728)

### Description of the issue

optimize sdk generate block api

### Issue-Type
- [ ] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [ ] Running latest version of code.
- [ ] This issue has not been reported earlier.

**Comment by gythialy** [comment] 2019-11-11 14:55
Duplicate of #35

**Closed as completed by gythialy** 2019-11-11 14:55 UTC
